### ISSUE TITLE
Large erosions failing

### ISSUE THREAD

**Issue by richardbeare** [richardbeare/LabelErodeDilate#11] opened 2018-09-05 01:57 UTC
commit 2fa42995c1285a975b165eb119755f35886bb429 fixes an issue reported on the mailing list earlier in the year. Large erosions were producing blank images. The problem was caused by incorrect numeric type when setting up boundary conditions. Two tests of large structuring elements have been included.

@hjmjohnson @fbudin69500 @jhlegarreta @ut666 : Not sure of how the InsightSoftwareConsortium fork is being updated wrt to threading architecture changes etc, so filing this issue so you can handle the merge in your preferred fashion.

**Comment by jhlegarreta** [comment] 2018-11-18 01:13
@richardbeare Sorry for the long delay. I had completely missed this. The upstream changes you mention were brought to the downstream ISC fork successfully:

https://github.com/InsightSoftwareConsortium/LabelErodeDilate/commit/2fa42995c1285a975b165eb119755f35886bb429

According to [this thread](https://discourse.itk.org/t/itk-external-module-github-builds-for-4-x-and-5-x/900) in discourse, CI images use the **latest ITK released, including alpha versions**:

https://hub.docker.com/r/insighttoolkit/module-ci/tags/

The CI is currently failing for unrelated reasons, so I'd say that the issue can be closed. If legacy release versions of ITK are used in the CI and the threading changes are not being checked against for this module, issues may arise in the future, so I'd say that we can re-open the issue then if the mentioned commit is the cause for those failures.

**Comment by jhlegarreta** [comment] 2018-11-18 01:41
That said, it would be nice if the test set (dataset, parameters, etc.) that caused the issue was incorporated to the current set of test cases, if not already done, for the sake of completeness.

**Comment by richardbeare** [comment] 2018-11-18 06:05
There are new tests as part of this fix - simply larger erosions/dilation than were tested previously. The problem arose at about 16 - as 16^2 is 256 and the bug was causing an 8 bit value to be used somewhere...

**Comment by jhlegarreta** [comment] 2018-11-18 14:10
👍 Thanks @richardbeare . Then, since it is being tested and has been solved, I'd be for closing the issue.

**Closed** 2018-11-18 20:29 UTC
